### ISSUE TITLE
Runtime error when ordering db sets

### ISSUE THREAD

**Issue by waleed-alharthi** [remihenache/ThreadSafeDbContext#2]
the code below
```
libraries = await Repository.Get<Library>()
                            .Where(x => x.Status != EntityStatus.Deleted && x.Status != EntityStatus.Deleted)
                            .OrderBy(x => x.Name)
                            .ToListAsync();
```

generates the following error
```
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
2023-10-12 19:04:01       Unhandled exception rendering component: Unable to cast object of type 'Microsoft.EntityFrameworkCore.ThreadSafe.QueryProviders.ThreadSafeQueryable`1[Clamp.Models.Library]' to type 'System.Linq.IOrderedQueryable`1[Clamp.Models.Library]'.
2023-10-12 19:04:01       System.InvalidCastException: Unable to cast object of type 'Microsoft.EntityFrameworkCore.ThreadSafe.QueryProviders.ThreadSafeQueryable`1[Clamp.Models.Library]' to type 'System.Linq.IOrderedQueryable`1[Clamp.Models.Library]'.
2023-10-12 19:04:01          at System.Linq.Queryable.OrderBy[TSource,TKey](IQueryable`1 source, Expression`1 keySelector)
2023-10-12 19:04:01          at Clamp.Features.Libraries.LibrariesPage.OnParametersSetAsync() in C:\Users\alhar\source\repos\Clamp\Clamp\Features\Libraries\LibrariesPage.razor:line 15
2023-10-12 19:04:01          at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
```

it runs fine when i exclude this part. As a workaround, i can order after loading the list.
`.OrderBy(x => x.Name)`

**Comment by remihenache** [comment]
I just release a version for it, some minutes ago :) (use version at least 1.0.6)
Tell me if it's ok now

**Comment by waleed-alharthi** [comment]
Just what the doctor ordered! I confirm ordering works fine now, many thanks!
